# Generated by Django 4.0.3 on 2022-04-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamheadless_publisher', '0002_describetenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describetenant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='described_tenant', to='iamheadless_publisher.item'),
        ),
    ]
